services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8181:8181"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - PORT=8181
      - HOST=0.0.0.0
      - RELOAD=True
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app/backend
    env_file:
      - .env
    restart: unless-stopped